### ISSUE TITLE
Type inference displays ‚any’ for ‚services‘ parameter

### ISSUE THREAD

**Issue by Lotes** [langium/djinject#8] opened 2022-11-26 10:39 UTC
I am not sure if this is a bug 🐞… during module writing, I miss type information of the factory parameter ([this line](https://github.com/Lotes/sqlite-undo-log/blob/e79ad8c31abc679d4905290f0a597a6db8629807/src/index.ts#L75) for example). Instead it displays ANY… what is wrong in my module definition?

**Comment by danieldietrich** [comment] 2022-12-09 16:38
It is not a bug, it is a feature. In fact, you may explicitly define the type you need per module/per factory :)

Finally, the inject function will collect all your factory parameters (each called "context") and calculate on the type level, if the needed dependencies are provided by any of your modules. Otherwise the compiler generates a very specific error.

I will elaborate on this in examples.

**Comment by danieldietrich** [comment] 2022-12-13 12:34
Update: It seems that there leaked a wrong type into djinject's `Module` definition:

```ts
type Module<C = any, T = C> = {
    [K in keyof T]: Module<C, T[K]> | Factory<any, T[K]>
                                              ^^^--- wrong
};
```

Fixing that (by setting `any` to `C` breaks a lot of tests ... I will look into that.

**Comment by danieldietrich** [comment] 2022-12-13 14:23
Current state:

1. the user defines the so-called container type `C`, e.g. `{ t: T }`
2. the user then passes the related Module to the `inject` function, e.g. `Module<{ t: T }> = { t: (ctx} => T }`, where the so-called Context `ctx` may have _any_ shape
3. the result of `inject` is the merged type of all arguments (read: Modules), which is `C` in the case of one Module. In the case of multiple Modules, all Contexts are inferred and Djinject checks that the resulting Container really provides all values aka services that are declared (out of nothing) in the Contexts.

The main problem with the Module definition above is that it can't infer the Contexts of the factory functions, anything is allowed. This is a feature and I want to keep it that way. We can achieve that by changing the usage of Djinject as follows:

1. the user defines just the Modules, without knowing the Container type. The Module definition allows the user to defined _untyped_ Contexts, like `{ t: (ctx) => T }`, in that case `ctx` is implicitly set to the container of that specific Module, e.g. `{ t: T }`. However, the user may also define a Context that differs from that Module, e.g. `{ t: (ctx: { u: U } =>  T}`, then the `inject` function will take care that the resulting Container (inferred from merging _all_ Modules) will contain `{ u: U }`.
2. the inject function then computes the Container type

I know that this description might be not-so-easy to understand. Changing Djinject that way is a breaking change regarding backward-compatibility. I will experiment a bit with it - this will be a non-trivial change throughout the whole Djinject library...

**Closed** 2023-01-03 22:57 UTC
Labels: bug
